### ISSUE TITLE
[Feature] falco-ignore

### ISSUE THREAD

**Issue by kevin-fagan** [ysugimoto/falco#110] opened 2022-10-03 15:10 UTC
Fastly VCL supports some hidden features such as `map` and `callback` that are undocumented. Falco does not support these functions which causes the lint to fail every time. I think it could be beneficial to include some way to tell Falco to ignore the next line, sub-routine, or file.

For example, if you use the `prettier` linter for JS, you can tell prettier to ignore the next line like such:

```js
// prettier-ignore
let positiveInts = test.map((value) => {
    if (value > 0) {
        return value
    }
})
```

We could potentially do the same with Falco:

```VCL
// falco-ignore
map(var.test, test_callback, ",");
```

This can also act as a bandaid to any unexpected bugs a developer might run into while using Falco. If a developer is experiencing some other linting issues that is causing their lint to fail, they can always tell Falco to skip the next like, sub-routine or file to resolve said issues until the linting bug can be patched.

**Comment by ysugimoto** [comment] 2022-10-04 17:45
Yes, long-time I'm thinking about it.
We'll try to implement that is able to ignore or suppress the error reporting mechanism.

**Comment by davinci26** [comment] 2022-10-05 00:16
huge +1 on this one

**Comment by shadialtarsha** [comment] 2022-10-05 09:32
I would like to discuss a proposal for implementing this feature with you here and then I can take it to implementation.

**Feature's Acceptance Criteria** 
1. 2 levels for ignoring will be introduced:
- On the subroutine level
- On the statement Level
2. This feature shouldn't interfere with the current semantic comments that falco has. To be more specific: Fastly macro comments and Scope comments 
3. Tokens should be parsed even with ignore in place. Ignoring's effect should only be during the linting phase.
4. (optional) Show what linting errors being ignored

**High-level implementation**
Introduce 2 new comments:
- `--falco-ignore`: Don't lint the next statement!
- `--faloc-sub-ignore`: Don't lint the next subroutine block

Inside the declaration of the subroutine and the statement, we will add a new field that indicates if any of them have these comments set! - Or we can use the `infixComment` - but I need to double check the impelementation of this comment.

With these two new comments, we introduce two new Flags to `Context`: 
- `falcoIgnore: false`
- `falcoSubIgnore: false`
setting and unsetting the values for these 2 flags will happen in 2 places: 
- `lintSubroutineDeclaration`
- `lintBlockStatement`

Suppressing the errors will happen based on the value of these flags.

So what do we think here? I would love to hear your feedback and your ideas!

**Comment by kevin-fagan** [comment] 2022-10-05 14:20
> Tokens should be parsed even with ignore in place. Ignoring's effect should only be during the linting phase.
(optional) Show what linting errors being ignored

This makes me wonder if we should allow the user to specify which errors / warnings they would like to ignore for a statement or sub-routine? Similar to ESLint or prettier? For example, with ESLint, I can ignore the next statement for a specific rule like such:

```JS
// eslint-disable-next-line no-use-before-define
var thing = new Thing();
```

**Comment by shadialtarsha** [comment] 2022-10-10 19:12
Thanks for feedback
I am proposing another solution and hope to get some feedback from you:

**Acceptance Criteria:**
1. `//falco-ignore-subroutine` will ignore linting errors in the next subroutine
2. `//falco-ignore-next-line` will ignore linting errors in the next line
3. `//falco-ignore-start` -> `//falco-ignore-end` will ignore linting errors between two lines
4. All the comments above take a space-separated list of `FalcoError` where users can specify which errors to ignore
 `//falco-ignore-subroutine invalid-type undefined-variable`
5. This feature shouldn't interfere with the current semantic comments that Falco has. To be more specific: Fastly macro comments and Scope comments.
6. Without a list of errors to ignore, all errors will be ignored.

**API Defination**
```
package context

type FalcoError string

const (
	InvalidNameErr                   FalcoError = "invalid-name"
	InvalidValueErr                    FalcoError = "invalid-value"
	InvalidTypeErr                     FalcoError = "invalid-type"
...
)

// falcoIgnore keeps track of Falco Ignore state during execution.
type falcoIgnore struct {
	ignoreNextSubroutine bool
	ignoreNextLine       bool
	ignoreRange          bool
	errorsToIgnore       map[FalcoError]bool
}

// newFalcoIgnore creates a new instance of Falco ignore.
func newFalcoIgnore() *falcoIgnore {
	return &falcoIgnore{}
}

// isEnabled checks if falco ignore is enabled currently.
func (fi *falcoIgnore) isEnabled() bool {
	return fi.ignoreNextSubroutine || fi.ignoreNextLine || fi.ignoreRange
}

// reset sets falco ignore state to initial state.
func (fi *falcoIgnore) reset() {
	fi.ignoreNextSubroutine = false
	fi.ignoreNextLine = false
	fi.ignoreRange = false
	fi.errorsToIgnore = map[FalcoError]bool{}
}

// addToErrorsToIgnore adds new error for falco ignore for falco to ignore it.
func (fi *falcoIgnore) addToErrorsToIgnore(e FalcoError) {
	fi.errorsToIgnore[e] = true
}

// shouldIgnoreError checks if falco should ignore the current error.
func (fi *falcoIgnore) shouldIgnoreError(e FalcoError) bool {
	_, ok := fi.errorsToIgnore[e]
	return ok
}
```

**Implementation**
`Context` will have an instance of `falcoIgnore` where its state is gonna change based on the comments above.
`LintError` will have a new field called `FalcoError` that defines the current error object and help us to check if we need to ignore it or not!

**Comment by kevin-fagan** [comment] 2022-10-13 22:32
@shadialtarsha I think this makes a lot of sense! I have not looked at the code very closely for this project, so I don't have a strong opinion about the API definition, but I think this is great! :)

**Comment by ysugimoto** [comment] 2023-03-29 15:44
@shadialtarsha 
Finally, I've started to think about this, and thank you for your proposals 👍 
Almost I agree with you, but just one thing we need to consider, @kevin-fagan says:

```
// falco-ignore
map(var.test, test_callback, ",");
```

The `map` should be ignored on the parser level, not the linter level.
Currently, I have no idea about that. Probably we should implement some kind of functions that come from Varnish.
This is because ignoring parser errors will occur unexpected behavior, for example, a user also could ignore the Syntax Error!

Therefore, we should support to ignore parser error with deep carefully

**Closed** 2023-04-26 02:55 UTC
